name: apu_filter_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # --- Dependencias de Conda (El núcleo científico) ---
  - python=3.10
  - faiss-cpu
  - mkl
  - pyarrow
  - numpy
  - scipy
  - scikit-learn
  - pip

  # --- Dependencias de Pip (El resto de la aplicación) ---
  - pip:
    - -r requirements.txt