name: apu_filter_env
channels:
  - pytorch  # Canal para faiss-cpu
  - conda-forge # Canal para otras dependencias científicas
  - defaults
dependencies:
  # --- Dependencias de Conda (El núcleo científico) ---
  - python=3.10
  - faiss-cpu
  - mkl
  - pyarrow
  - numpy
  - scipy
  - scikit-learn
  - pip