[tool.ruff]
line-length = 93
indent-width = 4

[tool.ruff.lint]
# Dejamos solo las reglas est√°ndar para errores, advertencias e imports.
select = ["E", "F", "W", "I"]

[tool.ruff.format]
quote-style = "double"

[project]
name = "apu-project"
version = "0.1.0"

[tool.setuptools]
packages = ["app"]